Repository GlueOps/cluster-information-help-page-html, pull requests merged in 2024-10, with the labels that each got.

#29 Update and rename ghcr.yaml to container_image.yaml
  .github/workflows/container_image.yaml
  .github/workflows/ghcr.yaml
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#27 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, configuration changes, sync

#26 chore(deps): update nginx:1.26.2-alpine docker digest to 5b44a5a
  Dockerfile
Labels: patch, include-in-release-notes, Review effort [1-5]: 1, auto-update, dependencies
